meta_product_name: "Chargesharing"
meta_title: "Chargesharing -  Book a charger for your Car"
meta_description: "Nice description here for anybody who wants to book a charger for his car"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@OGmusik"   # required for Twitter Cards
